### ISSUE TITLE
Add reviews

### ISSUE THREAD

**Issue by jonsger** [giggls/opencampsitemap#12] opened 2020-05-11 13:34 UTC
I think it would be a nice feature to have reviews from users for camp sites, like Google Maps it has.

But I don't think using Google or Yelp as a source is the right way.

There are atm two open systems for place reviews, I'm aware of:

[OpenPlaceReviews](https://openplacereviews.org) and [MangrooveReviews](https://mangrove.reviews/build). The latter has already a small documented API.

What do you think?

**Comment by giggls** [comment] 2020-05-11 13:49
Given the fact, that the main purpose of this Map is to **improve the tagging of campsites in Openstreetmap** this would be well beyond the scope of this Map.

I also have the strong feeling that this map should be about facts rather than on-objective things like how **good** or **bad** a site is in various aspects as this will almost certainly require some kind of Moderation.

However, adding links to some **external** review portal is something I can well imagine.

**Comment by carabasiru** [comment] 2020-05-11 14:33
Hi there, I'm part of the Mangrove team. Definitely understand the concerns about this going beyond the scope, and requiring additional work. 

To your point on un-objective things: having the possibility to interact, to store one's own evaluation, to share with others, and to learn from others' assessment has become a fundamental need for people today when they decide where to go or what to consume. That is what makes apps such as Google Maps or TripAdvisor so attractive. And that is also what will ultimately keep people within those proprietary, privacy-invading services: because they can get there more than just the factual data: they can get help in their decision-making, and share with others.

Here's a write-up about the Mangrove project and the tech that is available, including the algorithms to allow automated moderation. It is a philanthropic initiative and we invite people and organisations to join as members:  https://hackmd.io/@dinaca/BJiWeRIqL 

We also provide some modest amounts of funding for development work for integrations, if this helps. **Adding links** would definitely be a first step to at least getting more people to share their insights and opinions in a dataset that is open, privacy-respecting, and serving the public good :)

**Comment by giggls** [comment] 2020-05-11 15:52
Hm this map is **solely** based on data from Openstreetmap and I do not intent to change this anytime soon. My Intention was to create a map rather than some random tourist information stuff in the first place.

See my blog Posts about my motivation to create this map:
http://blog.gegg.us/2019/01/announcing-open-camping-map/
http://blog.gegg.us/2019/09/a-few-updates-on-open-camping-map/

Unfortunately tagging is still far from perfect. Still only 15.96% have a Website tag to illustrate this a little bit.

For referencing an external database we would need to invent an additional tag like we already have done for **Wikidata**. So this goes well beyond OpenCampingMap and should thus be discussed in a wider context.

Sven

**Comment by keorn** [comment] 2020-05-13 08:49
@giggls looks like a great project, it would be good to use OSM for camping more.

Regarding your idea with a tag, it sounds like a great idea for discoverability, but in case of Mangrove that may be redundant. Mangrove reviews can be identified by Geo URI, which can be derived from coordinates and name of the place, so extra tags would not add more information.

Going back to your initial suggestion, linking could be nice first step. We actually looked at campings thanks to another project already so will let you know what would be a nice link format to our web app if you would be fine including it.

Other than that, coming to your point on moderation. We have some systems to provide moderation ourselves for now, so you could rely on that. Another option is to simply stick to star ratings and rigid metadata fields (like context of visit), then there is less worry about abuse (but much less richness).

What do you think?

**Comment by wtimme** [comment] 2022-07-28 11:28
As an MVP, we could add a link to mangrove.reviews and provide the place's Geo URI as the `sub` parameter (e.g. https://mangrove.reviews/search?sub=geo%3A48.63182,8.31631%3Fz%3D17). That way, visitors of OpenCampingMap could easily check if there are any existing reviews, and use the mangrove.reviews website to add new ones.

What do you think, @giggls?

_Note: At the moment, the URL above gives an error. But in theory, that should work and show the reviews._

**Comment by wtimme** [comment] 2022-07-28 18:19
Thanks for your quick response! 👍 Wow, that does look exactly how I imagined it, thanks!

One small thing that I noticed while browsing the camp sites: Unnamed camp sites (such as [this one](https://camping.openstreetmap.de/map-dev/#14/48.6153/8.2019/1/1/bef)) seem to result in the `q` parameter to read "undefined". How about we hide the review link for those?

Other than that, I think this approach works quite well for a first MVP. 💪 Is there anything I can do to help? Again, thanks a lot for your effort!

**Comment by giggls** [comment] 2022-07-28 18:27
That was just a very quick hack with two lines of Javascript code.

I should probably add some css to make it look similar to the castle-map link.

Would be nice to have a real Mangrove entry for tests before deploying this to my "real" map.

Removed the link on unnamed sites now.

**Comment by wtimme** [comment] 2022-07-28 18:58
> Removed the link on unnamed sites now.

Thanks! I checked this using the link that I've posted above, and it works as expected.

> I should probably add some css to make it look similar to the castle-map link.

Could be a V2 in my opinion. The link alone is already a huge benefit.

> Would be nice to have a real Mangrove entry for tests before deploying this to my "real" map.

I have sent you a link to a review of mine via email. Let me know if that works for you.

**Comment by giggls** [comment] 2022-07-28 22:07
OK, added CSS and l10n. 
Tend to deploy this to the live map and close this issue.
Objections?

**Comment by jonsger** [comment] 2022-07-29 07:27
Hm, in map-dev the link name seems to be always `undefined (Mangrove)`. Is this intended?

**Comment by giggls** [comment] 2022-07-29 07:30
> Hm, in map-dev the link name seems to be always `undefined (Mangrove)`. Is this intended?

I can not reproduce this bug.

**Comment by jonsger** [comment] 2022-07-29 07:33
Ah sorry, the map was cached and the cache was old here. Bug went away :)

**Comment by wtimme** [comment] 2022-07-29 07:54
No objections. If people wanted to integrate the JS SDK of Mangrove they can open a new issue.

Thanks a lot for this quick addition, @giggls!

**Comment by giggls** [comment] 2022-07-29 08:06
If the campsite Name is a generic term the Mangrove result is somewhat strange.

Example: https://camping.openstreetmap.de/map-dev/#10/48.5157/8.2260/1/1/bef/way/52333477

**Comment by giggls** [comment] 2022-07-29 08:47
> No objections. If people wanted to integrate the JS SDK of Mangrove they can open a new issue.
> 
> Thanks a lot for this quick addition, @giggls!

Send me a pull request...

**Comment by giggls** [comment] 2022-07-29 09:09
OK, this is a very small change.
See commit https://github.com/giggls/opencampsitemap/commit/571d24e0c693d8127352aed9f16161609c1868a8
I will keep this issue open if someone wants to change this to Mangrove Javascript API.

**Comment by wtimme** [comment] 2022-07-30 10:19
> If the campsite Name is a generic term the Mangrove result is somewhat strange.

In the Mangrove URL for the camping site "Quellgrund" [here](https://camping.openstreetmap.de/map-dev/#10/48.5157/8.2260/1/1/bef/way/52333477), the name of the camping site is part of the URL's `q` parameter:

https://mangrove.reviews/search?sub=geo%3A48.808964214,8.583263464&q=Quellgrund

This results in "strange" search results, and the camping site is not visible, and thus cannot be reviewed.

However, the name can be moved to the Geo URI (as _its_ `q` parameter). Judging from the network traffic and Mangrove's response, the "uncertainty" parameter (`u`) has to be provided as well, in order to properly find the reviews, which I hard-coded to 50. Here's the full URL:

https://mangrove.reviews/search?sub=geo%3A48.808964214,8.583263464%3Fq%3DQuellgrund%26u%3D50

That way, the camping site _is_ visible, and it looks like it can be reviewed.

I am not sure whether a fixed "uncertainty" of 50 is the best approach here. According to [Mangrove's documentation](https://mangrove.reviews/standard#mangrove-core-uri-schemes), 

> Query string for this [GEO] URI (content following ?) [...] MAY contain a field `u=` for which the value indicates an approximate radius of the place in meters which SHOULD not be greater than 40000000.

**Comment by giggls** [comment] 2022-07-31 09:52
Hm do I need to replace & by ?

**Comment by lyxys** [comment] 2022-07-31 12:17
I suggest you try it with replacing & with %3F, the "?" has to be url-encoded because otherwise the query string would break url syntax. mangrove apparently builds querystrings like "sub=geo:<coords>?q=<name>&u=<meters>" with the whole strings after the first "=" being url-encoded. No idea how they handle names containing "?" or "&", maybe double encoding

**Comment by lyxys** [comment] 2022-07-31 12:19
Gihub eats away stuff that looks like tags, so try the last part again:

`mangrove apparently builds querystrings like "sub=geo:?q=&u=" with the whole strings after the first "=" being url-encoded. No idea how they handle names containing "?" or "&", maybe double encoding`

**Comment by lyxys** [comment] 2022-07-31 12:29
As mangrove pulls the location data from openstreetmap, the "u" parameter appears to be not necessary. However, if someone slightly moves a POI, previous reviews might not be found? So i suggest to add a fixed uncertainty value for now; mangrove apparently uses 30 themselves.

**Comment by lyxys** [comment] 2022-07-31 12:32
Testing with the campsite "Am Eichelberg" in Bruchsal, it is not found at all using "&q=", instead it finds loads of stuff with an address of "Am Eichelberg", NOT including the campsite. Using "%3Fq=" finds the campsite and ONLY the campsite.

**Comment by giggls** [comment] 2022-07-31 12:39
We will definitely figure how escaping & works as & is not that uncommon in campsite names.

This query gives me 1648 sites:

``sql
SELECT count(*) FROM osm_poi_campsites WHERE tags->'name' LIKE '%&%';
``
Picking a random one:
https://opencampingmap.org/#16/48.5225/-111.8635/1/1/bef/way/1076907317

**Comment by giggls** [comment] 2022-07-31 13:16
Without escaping & and ? yet I got this now:
https://camping.openstreetmap.de/map-dev/
comments?

**Comment by giggls** [comment] 2022-07-31 13:25
Unfortunately this does not work as expected if there are reviews like here:
https://camping.openstreetmap.de/map-dev/#16/48.0745/9.1273/0/1/bef

You don't get the reviews util jou select the result :(

**Comment by lyxys** [comment] 2022-07-31 13:28
Kind of works, it even allows "&" in names if the name itself is url-encoded. However, it apparently ignores the geo-parameter at least sometimes, the "Lewis & Clark" campground from your previous example is not found, but is (with a truncated name) if the "?" is url-encoded. According to mangrove core uri schemes, q MUST be part of the "geo" claim.

**Comment by lyxys** [comment] 2022-07-31 13:31
url-encoding "?" (and "&" if using the "u=" optional parameter) works fine for me in all cases except when there is a "&" as part of the name.

**Comment by giggls** [comment] 2022-07-31 13:36
> url-encoding "?" (and "&" if using the "u=" optional parameter) works fine for me in all cases except when there is a "&" as part of the name.

This is what the code at https://camping.openstreetmap.de/map-dev/ now does. But unfortunately the need to click to view existing reviews bug preveals, right?

Should the name also be URL-encoded?

**Comment by lyxys** [comment] 2022-07-31 13:36
I take that back, I too have the problem that I have to click the search result to see the reviews. At least I get the information that there ARE reviews, though

**Comment by lyxys** [comment] 2022-07-31 13:39
according to the mangrove core uri schemes, the q parameter needs to use uri compliant percent encoding (aka url-encoding) and should not exceed 100 characters

**Comment by giggls** [comment] 2022-07-31 13:45
Which still has this bug that an existing review is not shown...
I did add an encodeURI function code now but still broken:
https://camping.openstreetmap.de/map-dev/#16/48.0760/9.1241/1/1/bef/way/885634787
https://mangrove.reviews/search?sub=geo%3A48.078330185,9.128217299%3Fq=Jugendzeltplatz%20Nr.%207%26u%3D30

**Comment by lyxys** [comment] 2022-07-31 13:56
This seems to be a bug (?) in mangrove: If you follow the review link from tha mangrove start page, you get displayed the review immediately. However, if you copy that link and call it directly (i.e. without the referrer pointing to mangrove itself) you get the search result and have to click it to see the review.

**Comment by giggls** [comment] 2022-07-31 13:58
Hm can we open issues at mangrove?

**Comment by lyxys** [comment] 2022-07-31 14:03
That we cant have a "&" in names in the geo search parameter seems to be a bug in the mangrove core uri scheme. The geo scheme is apparently modeled on the android map search api, which has a url-encoded q=name parameter. However, they have any additional parameters as separate query variables, using a non-escaped "&" as separator. mangrove included the optional "u" parameter as part of the geo scheme and therefore need to escape the "&" separator, with the result that "&" can not be part of the "q" search value.

**Comment by giggls** [comment] 2022-07-31 14:05
Oh I would not want to issue this as a bug but this need to click thing.

**Comment by lyxys** [comment] 2022-07-31 14:10
Mangrove uses gitlab at https://gitlab.com/open-reviews/mangrove
There is already an issue about "&" in place names, untouched since 8 months.
The project seems a bit quiet, last update 7 months ago …

**Comment by giggls** [comment] 2022-07-31 14:11
OK, I will open an issue about this need to click thingy.

**Comment by giggls** [comment] 2022-07-31 14:13
*argh* I don't have an account on gitlab.com

**Comment by lyxys** [comment] 2022-07-31 14:21
Regardless of the "click to view" issue, please use the url-encoded value for the sub= parameter or at least %3F instead of "?" in it because it works a lot better that way.

**Comment by giggls** [comment] 2022-07-31 14:35
Ähm, I already have this.
This is how the code currently look like:
```Javascript
mangrove_url='https://mangrove.reviews/search?sub=geo%3A' + fdata.geometry.coordinates[1] + ',' + fdata.geometry.coordinates[0] + '%3Fq=' + encodeURI(fdata.properties.name) + '%26u%3D30';
```

**Comment by lyxys** [comment] 2022-07-31 14:44
sorry, I had looked at a window that had been open for quite a while. If you want to follow the mangrove spec, make it 
`mangrove_url='https://mangrove.reviews/search?sub=' + encodeURI('geo:' + fdata.geometry.coordinates[1] + ',' + fdata.geometry.coordinates[0] + '?q=' + fdata.properties.name + '&u=30');`
Makes it more readable to IMHO

**Comment by giggls** [comment] 2022-07-31 14:47
OK, see: https://github.com/giggls/opencampsitemap/commit/61ab239efdc57fb009b365d38836c3dcd628c87c

**Comment by giggls** [comment] 2022-07-31 14:48
*argh* does not seem to work anymore this way!

**Comment by lyxys** [comment] 2022-07-31 14:52
weird, can we compare the created links?

**Comment by giggls** [comment] 2022-07-31 14:53
Yes ? and & are not encoded.

**Comment by giggls** [comment] 2022-07-31 14:55
I will likely need encodeURIComponent()

**Comment by giggls** [comment] 2022-07-31 14:56
encodeURI() will not encode: ~!@#$&*()=:/,;?+'

**Comment by lyxys** [comment] 2022-07-31 14:56
yup, I just looked it up, so encodeURIComponent() is needed

**Comment by wtimme** [comment] 2022-08-03 11:30
I have created a draft pull request (#27) in which the reviews are retrieved from Mangrove and directly displayed on OpenCampingMap when selecting a camp site. Take a look:

<img width="408" alt="Screenshot 2022-08-03 at 13 24 18" src="https://user-images.githubusercontent.com/1681085/182597327-e92fe918-f82f-4986-a2e3-3fc040be835f.png">

Clicking the icon next to the stars rating opens the review on Mangrove in a new tab.

Let me know what you think. I'm also happy for code review feedback.

**Comment by giggls** [comment] 2022-08-03 11:47
> I have created a draft pull request (#27) in which the reviews are retrieved from Mangrove and directly displayed on OpenCampingMap when selecting a camp site.

Now running on https://camping.openstreetmap.de/map-dev/

Please test!

**Closed** 2022-08-18 10:47 UTC
